teebb_uploader:
#    upload_dir: '%kernel.project_dir%/public/teebb_uploader'
#    namer: 'teebb.uploader.namer.php_namer'
#        service: 'teebb.uploader.namer.hash_namer'
#        options:
#            length: 10
#    storage: serviceID
    handlers:
        simple_file_handler:
            entity: 'App\Entity\SimpleFile'
            upload_dir: '%kernel.project_dir%/public/teebb_uploader'
            uri_prefix: 'teebb_uploader'

        name2:
            entity: 'App\Entity\SimpleFile'
            upload_dir: '%kernel.project_dir%/public/teebb_uploader2'
            uri_prefix: 'temp'
            namer:
                service: 'teebb.uploader.namer.hash_namer'
                options:
                    length: 10